bind C-b
set -g prefix F10 # F10 was changed to CAPS-LOCK in os.

set -sg escape-time 0

bind l resize-pane -L 5
bind r resize-pane -R 5
bind | split-window -h
bind - split-window -v
bind  Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R
bind a new-window
bind-key N command-prompt -p "New session name:" "new-session -s '%%'"
bind x kill-pane

set -g history-limit 100000
set -g mouse on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind s choose-tree -ZsK '#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}'

bind R source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"


set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'moon'
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_date_time '%d-%m-%Y %H:%M' # It accepts the date UNIX command format (man date for info)

set -g @rose_pine_bar_bg_disabled_color_option 'default'

set -g @rose_pine_window_status_separator " | " # Changes the default icon that appears between window names
set -g @rose_pine_disable_active_window_menu 'on' # Disables the menu that shows the active window on the left

set -g @rose_pine_show_current_program 'on' # Forces tmux to show the current running program as window name
set -g @rose_pine_show_pane_directory 'on' # Forces tmux to show the current directory as window name

set -g @rose_pine_window_separator ' : ' # Replaces the default `:` between the window number and name

run '~/.tmux/plugins/tpm/tpm'

